<?php

return [
    'stop_words' => [
        'a',
        'ante',
        'bajo',
        'cabe',
        'con',
        'contra',
        'de',
        'desde',
        'durante',
        'en',
        'entre',
        'hacia',
        'hasta',
        'mediante',
        'para',
        'por',
        'segun',
        'según',
        'sin',
        'so',
        'sobre',
        'tras',
        'el',
        'la',
        'los',
        'las',
        'un',
        'una',
        'unos',
        'unas',
        'lo',
        'al',
        'del',
        'y',
        'o',
        'u',
        'e',
        'que',
        'se',
        'su',
        'sus',
        'mi',
        'mis',
        'tu',
        'tus',
        'es',
        'son',
        'fue',
        'ser',
        'estar',
        'this',
        'that',
        'the',
        'of',
        'on',
        'in',
        'at',
        'to',
        'for',
        'and',
        'or'
    ],
    'field_boosts' => [
        'title' => 3.5,
        'location' => 2.0,
        'description' => 1.0,
    ],
    'phrase_boost' => [
        'title' => 5.0,
        'description' => 2.0,
    ],
    'candidate_limit' => 300,

    'popularity_alpha' => 0.15,

    'term_click_boost' => 3,

    'click_beta' => 0.02,
    'click_cap'  => 100,
];
